version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: new_school
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6000:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev.dev
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/new_school
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
volumes:
  postgres_data:
