FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONUTF8=1

WORKDIR /app

# Устанавливаем системные зависимости
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# Копируем только requirements.txt
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Не копируем весь код! Код монтируем из хоста
RUN mkdir -p /app/uploads

EXPOSE 8000
# Запустим FastAPI в режиме --reload (следит за файлами)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
